name: Docker Compose Deploy CI

on:
    push:
        branches: ["master"]
    workflow_dispatch:

jobs:
    stop:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3

            - name: Make sure everything is correctly installed
              run: |
                if ! command -v docker &> /dev/null
                  then
                    echo "Cannot find docker, please install docker first"
                    exit
                  fi
              shell: bash

            - name: Stop docker containers
              run: docker compose down --remove-orphans

            - name: Remove old images
              run: docker rmi $(docker images 'qizz-backend-app' -a -q)
    build:
        needs: stop
        runs-on: self-hosted

        steps:
            - name: Create secret .env file
              run: 'echo "$SECRET" > .env'
              shell: bash
              env:
                  SECRET: ${{ vars.ENV }}

            - name: Build docker images
              run: docker compose build

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Deploy docker images
              run: docker compose up -d